---
title: "Overview of EOPF Zarr Products"
format: html
---
### Introduction

In previous chapters, we introduced the **Earth Observation Processing Framework** (EOPF) initiative and explored the advantages of cloud-optimised formats like Zarr. <br>
Now, it is time to discover the actual EOPF Zarr products.<br>
ESA has made available the EOPF STAC Catalog. This catalog acts like a digital library, allowing us to easily find and understand the various EOPF Zarr datasets available.

### What we will learn

- 📚 What is the **EOPF STAC Catalog**, and why is it important
- 💾 How are EOPF Zarr products organised within the **STAC Catalog**.
- 🛰️ Which specific missions can we find in the  **EOPF STAC Catalog**.


<hr>

## Available EOPF Zarr products
Re-engineered EOPF Zarr products are available for exploration via the [EOPF Sentinel Zarr Sample Service STAC Catalog](https://stac.browser.user.eopf.eodc.eu/?.language=en).
Data from Sentinel-1, Sentinel-2 and Sentinel-3 missions are being re-processed and made available.

::: {.callout-important}
The re-processing from the Sentinel missions is an ongoing activity as part of the [EOPF Sentinel Zarr Sample Service](https://zarr.eopf.copernicus.eu/). This page and our tutorials will continuously be updated as soon as new data products are available.
:::

An overview of the datasets that are being re-engineered for different processing levels is given below.

### Sentinel-1
Sentinel-1 is a radar imaging mission that is composed of a constellation of two polar-orbiting satellites providing continuous all-weather, day and night imagery.

| Product | Instrument | Description | Available at |
|:---------|:---------|:---------|:---------|
| Level-1 GRD| Ground Range Detected | The Sentinel-1 Level-1 GDR products consist of focused SAR data that has been detected, multi-looked and projected to ground range using the Earth ellipsoid model WGS84. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-1-l1-grd?.language=en) |
| Level-1 SLC | Single Look Complex ( | The Sentinel-1 Level-1 SLC products consist of focused SAR data, geo-referenced using orbit and attitude data from the satellite, and provided in slant-range geometry. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-1-l1-slc?.language=en) |
| Level-2 OCN | Ocean | The Sentinel-1 Level-2 OCN products for wind, wave and currents applications may contain the following geophysical components derived from the SAR data: Ocean Wind field (OWI), Ocean Swell spectra (OSW), Surface Radial Velocity (RVL). | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-1-l2-ocn?.language=en) |


### Sentinel-2 
Sentinel-2 acquires optical imagery at high spatial resolution (10m to 60m) over land and coastal waters. The mission supports applications such as agricultural monitoring, emergency management, land cover classifications, and water quality.

| Product | Instrument | Description | Available at |
|:---------|:---------|:---------|:---------|
| Level-1C | Multi-Spectral Instrument | The Sentinel-2 Level-1C product is composed of 110x110 km2 tiles (ortho-images in UTM/WGS84 projection). Earth is subdivided on a predefined set of tiles, defined in UTM/WGS84 projection and using a 100 km step. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-2-l1c) |
| Level-2A | Multi-Spectral Instrument | The Sentinel-2 Level-2A Collection 1 product provides orthorectified Surface Reflectance (Bottom-Of-Atmosphere: BOA), with sub-pixel multispectral and multitemporal registration accuracy. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-2-l2a) |

### Sentinel-3

Sentinel-3 is a mission that regularly measures our Earth's oceans, land, rivers, lakes, ice on land, sea ice, and the atmosphere. Its goal is to keep track of and help us understand how these large parts of our planet change over long periods.

#### Ocean and Land Colour Instrument

| Product | Product | Description | Available at |
|:---------|:---------|:---------|:---------|
| Level-1 EFR | Earth Full Resolution | Provides TOA radiances at full resolution for each pixel in the instrument grid, each view and each OLCI channel, plus annotation data associated to OLCI pixels. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-3-olci-l1-efr) |
| Level-1 ERR | Earth Reduced Resolution | The Sentinel-3 OLCI L1 ERR product provides TOA radiances at reduced resolution for each pixel in the instrument grid, each view and each OLCI channel, plus annotation data associated to OLCI pixels. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-3-olci-l1-err) |
| Level-2 LFR | Land Full Resolution | The Sentinel-3 OLCI L2 LFR product provides land and atmospheric geophysical parameters computed for full resolution. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-3-olci-l2-lfr) |
| Level-2 LRR | Land Reduced Resolution | The Sentinel-3 OLCI L2 LRR product provides land and atmospheric geophysical parameters computed for reduced resolution. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-3-olci-l2-lrr) |

#### Sea and Land Surface Temperature Radiometer

| Product | Data | Description | Available at |
|:---------|:---------|:---------|:---------|
| Level-1 RBT | Radiance Brightness Temperature | The Sentinel-3 SLSTR Level-1B RBT product provides radiances and brightness temperatures for each pixel in a regular image grid for each view and SLSTR channel. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-3-slstr-l1-rbt) |
| Level-2 LST | LST: Land Surface Temperature | The Sentinel-3 SLSTR Level-2 LST product provides land surface temperature. | [this link](https://stac.browser.user.eopf.eodc.eu/collections/sentinel-3-slstr-l2-lst) |


## Conclusion

During this chapter, we took a guided tour of the **EOPF STAC Catalog**, seeing firsthand how it serves as a gateway to the wealth of **EOPF Zarr** products.<br>
We learned how these cloud-optimised datasets are organised and described, from their general structure to the specific information they include, making them discoverable and usable.


## What's next?
In the following chapter, we dive deeper into `EOPF Zarr` format and we start with practically working with EOPF Zarr datasets.
Also, in the [Explore the web interface of the EOPF Zarr STAC Catalog](32_eopf_stac_zarr_tutorial.qmd) we will showcast how to navigate this catalog, and you will be equipped to confidently explore and access a wide range of Sentinel mission data transformed into the efficient EOPF Zarr format.
