---
title: "**Glossary**"
format: html
---

Here we introduce some helpful terms that are mentioned throughout the EOPF 101.

| Acronym | Definition |
|:---|:---|
| **EOPF** | Earth Observation Processing Framework |
| **CDSE** | Copernicus Data Space Ecosystem |
| **COG** | Cloud Optimised GeoTIFF |
| **CMP** | Core Python Modules |
| **CRS** | Coordinate Reference System |
| **dNBR** | Delta Normalized Burn Ratio |
| **DN** | Digital Number |
| **EO** | Earth Observation |
| **EFFIS** | European Forest Fire Information System |
| **EPSG** | European Petroleum Survey Group |
| **FCI** | False Colour Image |
| **GCP** | Ground Control Points |
| **GRD** | Ground Range Detected |
| **HEALPix** | Hierarchical Equal Area isoLatitude Pixelation |
| **LST** | Land Surface Temperature |
| **NBR** | Normalized Burnt Ratio |
| **NIR** | Near-Infrared |
| **NRB** | Normalized Radar Backscatter |
| **SAFE** | Standard Archive Format for Europe |
| **SAR** | Synthetic Aperture Radar |
| **SCL** | Scene Classification Layer |
| **SLC** | Single Look Complex |
| **SLSTR** | Sea and Land Surface Temperature Radiometer |
| **SNAP** | Sentinel Application Platform |
| **STAC** | Spatio Temporal Asset Catalog |
| **SWIR** | Short-Wave Infrared |
| **TCI** | True Colour Image |
| **Zarr** | Cloud-optimised version for `netCDF` and `HDF5` formats, specifically designed for storing and accessing large n-dimensional arrays |

