---
title: "**References**"
format: html
---


Here, we make available powerful resources that can help you complement all the concepts we have introduced in this book. <br>
Fell free to complement 

# Geospatial Resources Overview

This table provides a categorized overview of key resources related to Earth Observation data processing, formats, and platforms.

| Category                      | Resource Title                                                                    | Description & Context                                                                                                                                              | Link                                                                                                                                                                                                                                                                                              |
|:------------------------------|:----------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Sentinel Mission & Product Specifications** | Sentinel-1 Level 1 Product Specification                                          | Detailed specifications for Sentinel-1 Level 1 products.                                                                                                           | [Available here](https://s1.pages.eopf.copernicus.eu/s1-l12-rp/main/pfs/level_1_product_specification.html)                                                                                                                                                                                                |
|                               | Sentinel 2 - MSI - Level 2A Products                                              | Auxiliary and data product specifications for Sentinel-2 MSI Level 2A products.                                                                                    | [Available here](https://s2.pages.eopf.copernicus.eu/pdfs-adfs/MSI/L2/PDFS_S2_MSI_L2.myst.html)                                                                                                                                                                                                         |
|                               | Sentinel-3 – Documentation (via CDSE)                                             | Comprehensive documentation for Sentinel-3 data products and mission.                                                                                              | [Available here](https://documentation.dataspace.copernicus.eu/Data/SentinelMissions/Sentinel3.html)                                                                                                                                                                                                  |
| **EOPF Platform & Modules** | Supported Products Formats — EOPF - Core Python Modules                           | Guide to the product formats supported by the Earth Observation Processing Framework's (EOPF) Core Python Modules.                                                 | [Available here](https://cpm.pages.eopf.copernicus.eu/eopf-cpm/main/eoproduct-user-guide/supported_formats.html)                                                                                                                                                                                      |
|                               | EOPF Sentinel Zarr Samples Service STAC Catalog                                   | A STAC (Spatio Temporal Asset Catalog) for accessing Sentinel Zarr samples hosted by EOPF.                                                                         | [Available here](https://stac.browser.user.eopf.eodc.eu/?.language=en)                                                                                                                                                                                                                                |
|                               | EOPF Sentinel Zarr Samples                                                        | Direct access to Sentinel data samples stored in Zarr format within the EOPF ecosystem.                                                                            | [Available here](https://zarr.eopf.copernicus.eu/)                                                                                                                                                                                                                                                    |
| **Data Formats & Standards** | Zarr Documentation                                                                | Official documentation for the Zarr format, a cloud-optimised standard for n-dimensional arrays.                                                                   | [Available here](https://zarr.dev/)                                                                                                                                                                                                                                                                   |
|                               | Introduction to the Zarr Format \| Copernicus Marine Help Center                  | An introductory guide to the Zarr format, provided by the Copernicus Marine Help Center.                                                                           | [Available here](https://help.marine.copernicus.eu/en/articles/10401542-introduction-to-the-zarr-format)                                                                                                                                                                                              |
|                               | Zarr + STAC                                                                       | Article discussing the integration and benefits of combining Zarr data with STAC catalogs.                                                                         | [Available here](https://element84.com/software-engineering/zarr-stac/)                                                                                                                                                                                                                               |
|                               | Is Zarr the new COG?                                                              | An insightful discussion comparing Zarr with Cloud Optimised GeoTIFF (COG) for cloud-native geospatial data.                                                       | [Available here](https://element84.com/software-engineering/is-zarr-the-new-cog/)                                                                                                                                                                                                                     |
|                               | About STAC                                                                        | General information and principles behind the Spatio Temporal Asset Catalog (STAC) specification.                                                                  | [Available here](https://stacspec.org/en/about/)                                                                                                                                                                                                                                                      |
| **Cloud-Native Geospatial Initiatives** | Cloud-Native Geospatial Forum (CNG)                                             | The official website for the Cloud-Native Geospatial Forum, promoting cloud-native approaches in geospatial.                                                       | [Available here](https://cloudnativegeo.org/)                                                                                                                                                                                                                                                         |