# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
#
proxy:
  https:
    enabled: true
    hosts:
      - eopf-toolkit-dev.ds.io
    letsencrypt:
      contactEmail: ciaran@developmentseed.org
hub:
  config:
    GitHubOAuthenticator:
      oauth_callback_url: https://eopf-toolkit-dev.ds.io/hub/oauth_callback
      allowed_organizations:
        - eopf-toolkit
      scope:
        - read:org
    JupyterHub:
      authenticator_class: github
      admin_users:
        - ciaransweet
  extraEnv:
    OAUTH_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: github-oauth-secret
          key: client-id
    OAUTH_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: github-oauth-secret
          key: client-secret
  extraConfig:
    01-oauth: |
      c.GitHubOAuthenticator.client_id = os.environ["OAUTH_CLIENT_ID"]
      c.GitHubOAuthenticator.client_secret = os.environ["OAUTH_CLIENT_SECRET"]
singleuser:
  image:
    # This `latest` should ideally be replaced during CI deployments
    name: 4zm3809f.c1.de1.container-registry.ovh.net/eopf-toolkit-python/eopf-toolkit-python
    tag: "latest"
    pullSecrets:
      - name: regcred
  profileList:
      - display_name: "Python"
        description: "Python environment powered by eopf-toolkit-python"
        default: true
      - display_name: "R"
        description: "R environment powered by eopf-toolkit-r"
        kubespawner_override:
          image: 4zm3809f.c1.de1.container-registry.ovh.net/eopf-toolkit-r/eopf-toolkit-r:latest
          pullSecrets:
            - name: regcred
