FROM quay.io/jupyter/r-notebook:python-3.12.10

RUN pip install pdm

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    libcurl4-openssl-dev \
    libssl-dev \
    libudunits2-dev \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    libfribidi-dev \
    libharfbuzz-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libxml2-dev \
    pandoc \
    curl \
    cmake \
    && rm -rf /var/lib/apt/lists/*

COPY ../pyproject.toml /home/${NB_USER}/deps/pyproject.toml
RUN chown -R ${NB_UID}:${NB_GID} /home/${NB_USER}/deps

RUN curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb \
    && dpkg -i quarto-linux-amd64.deb \
    && rm quarto-linux-amd64.deb

USER ${NB_UID}

WORKDIR /home/${NB_USER}/deps 

# Python Deps
RUN pdm config python.use_venv false && \
    pdm lock && \
    pdm export --without-hashes --format requirements | pip install -r /dev/stdin

WORKDIR /home/${NB_USER}

RUN rm -rf deps

# R Deps
RUN R -e "install.packages('rstac', repos='https://cran.rstudio.com/')"
RUN R -e "install.packages('tidyverse', repos='https://cran.rstudio.com/')"
RUN R -e "install.packages('stars', repos='https://cran.rstudio.com/')"
RUN R -e "install.packages('terra', repos='https://cran.rstudio.com/')"
RUN R -e "install.packages('httr2', repos='https://cran.rstudio.com/')"
RUN R -e "install.packages('fs', repos='https://cran.rstudio.com/')"
RUN R -e "install.packages('lobstr', repos='https://cran.rstudio.com/')"
RUN R -e "install.packages('BiocManager', repos='https://cran.rstudio.com/')"
RUN R -e "BiocManager::install('Rarr')"
RUN R -e 'install.packages("IRkernel", repos="https://cran.rstudio.com/"); IRkernel::installspec(user = FALSE)'
