FROM quay.io/jupyter/base-notebook:python-3.12.10

RUN pip install uv

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

ENV PATH=${CONDA_DIR}/bin:$PATH

COPY ../pyproject.toml /home/${NB_USER}/deps/pyproject.toml
COPY ../uv.lock /home/${NB_USER}/deps/uv.lock

RUN chown -R ${NB_UID}:${NB_GID} /home/${NB_USER}/deps

USER ${NB_UID}

WORKDIR /home/${NB_USER}/deps 

ENV UV_PROJECT_ENVIRONMENT=${CONDA_DIR}

RUN uv sync --frozen --no-install-project --inexact

WORKDIR /home/${NB_USER}
RUN rm -rf deps
