name: Delete old image tags from GHCR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

permissions: {}

jobs:
  delete-old-tags:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old eopf-toolkit-python image tags from GHCR
        uses: developmentseed/container-registry-cleanup@f590615d76bd127b94f30e12cfcda9ba6072247a # v0.2.1
        env:
          REGISTRY_TYPE: ghcr
          REPOSITORY_NAME: eopf-toolkit-python
          GITHUB_REPO_OWNER: eopf-toolkit
          VERSION_PATTERN: ^(release-.*|latest|competition)$
          TEST_RETENTION_DAYS: 7
          DRY_RUN: false

      - name: Delete old eopf-toolkit-r image tags from GHCR
        uses: developmentseed/container-registry-cleanup@f590615d76bd127b94f30e12cfcda9ba6072247a # v0.2.1
        env:
          REGISTRY_TYPE: ghcr
          REPOSITORY_NAME: eopf-toolkit-r
          GITHUB_REPO_OWNER: eopf-toolkit
          VERSION_PATTERN: ^(release-.*|latest|competition)$
          TEST_RETENTION_DAYS: 7
          DRY_RUN: false
